use restaurant_review;
CREATE TABLE IF NOT EXISTS `restaurant_review`.`restaurant1` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `images` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `operating_hours` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `cost` VARCHAR(10) NOT NULL,
  `cuisine` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `overall_rating_star` VARCHAR(25) NOT NULL,
  `establishment_type` VARCHAR(100) NULL,
  `website` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB;


INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (1, 'Seoul Garden @ NEX', 'Seoul Garden serves halal buffet korean barbeque.', 'images/t_seoulgarden.jpg', 'images/img_seoulgarden.jpg', '23 Serangoon Central, #B1-34/35 NEX, Singapore 556083', '11.30am - 10.30pm', '6555 1339', '$$$', 'Korean', 'North-East', 'Dinner', '4 Star', 'Restaurant', 'https://www.seoulgarden.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (2, 'Thai Express @ AMK Hub', 'Thai Express serves delicious thai dishes which will help you fufil your taste buds.', 'images/t_thaiexpress.jpg', 'images/img_thaiexpress.jpg', '53 Ang Mo Kio Ave 3, #02-26 AMK Hub, Singapore 569933', '11am - 10pm', '6481 0857', '$$', 'Thai', 'North-East', 'Lunch', '3 Star', 'Restaurant', 'https://thaiexpress.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (3, 'Takagi Ramen', 'Takagi Ramen is a small ramen store located in the heart of Ang Mo Kio which serves authentic japanese dishes such as ramen and curry rice.', 'images/t_takagiramen.jpg', 'images/img_takagiramen.jpg', '51 Ang Mo Kio Ave 3, #01-01C, Singapore 569922', '11am - 12am', '9170 7870', '$', 'Japanese', 'North-East', 'Lunch', '5 Star', 'Restaurant', 'https://takagiramen.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (4, 'Monster Curry @ Vivo City', 'Monster Curry serves yummy Japanese Curry Rice in MASSIVE portions. It also allows customers to select their level of spiciness as well.', 'images/t_monstercurry.jpg', 'images/img_monstercurry.jpg', '1 Harbourfront Walk #02-126/127 & 129, Vivo City, 098585', '11am - 10pm', '6221 3308', '$$', 'Japanese', 'Central', 'Dinner', '4.5 Star', 'Restaurant', 'https://www.monstercurry.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (5, 'Lau Pa Sat', 'Lau Pa Sat, also known as the Telok Ayer Market is one of the most popular food markets located in the heart of the financial district of Singapore. Lau Pa Sat serves local delicacies like satay, cicken rice, kaya toast, as well as many other dishes of other cuisines.', 'images/t_laupasat.jpg', 'images/img_laupasat.jpg','18 Raffles Quay, Singapore 048582', 'Open 24 hours', '6220 2138', '$$', 'Variety', 'Central', 'Dinner', '4 Star', 'Hawker', 'http://www.laupasat.biz/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (6, 'Newton Food Centre', 'Walking distance from Newton MRT station, the Newton Food Centre serves a wide variety of food from many different cuisines. It is a lively place with scrumptious delicacies where you can get a taste of everything yummy!', 'images/t_newton.jpg', 'images/img_newton.jpg', '500 Clemenceau Avenue North, Newton Food Centre, Singapore 229495', '12pm - 2am', 'N.A.', '$$', 'Variety', 'Central', 'Dinner', '4 Star', 'Hawker', 'N.A.');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (7, 'So Pho @ ION Orchard', 'Indulge yourself into delicious Veitnamese foods such as pho, banh mi, spring roll and Banh Xeo Vietnamese pancake.', 'images/t_sopho.jpg', 'images/img_sopho,jpg', '2 Orchard Turn, #B3-19 ION Singapore, Singapore 238801', '11am - 10pm', '6634 0571', '$$', 'Vietnamese', 'Central', 'Dinner', '3.5 Star', 'Restaurant', 'http://www.sopho.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (8, '19Tea', '19Tea is a Cafe located at Our Tampines Hub. 19Tea is originally from Korea where they had over 40 outlets around the country. They serve bubble tea, souffle pancakes and other desserts at affordable prices.', 'images/t_19tea.jpg', 'images/img_19tea.jpg', '1, #01-82 Tampines Walk, 528523', '11am - 10pm', 'N.A.', '$', 'Korean', 'East', 'Cafe', '4.5 Star', 'Cafe', 'https://www.facebook.com/19TeaSG/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (9, 'Awfully Chocolate @ JEM', 'Awfully Chocolate sells handmade and fresh baked desserts. Its chocolate desserts are absolutely rich and creamy. Nothing but simple quality cakes that star the velvety creaminess of their chocolate.', 'images/t_awfully.jpg', 'images/img_awfully.jpg', 'Jem, #01-15, 50 Jurong Gateway Rd, 608549', '10am - 10pm', '6734 1530', '$$', 'French', 'West', 'Cafe', '4 Star', 'Cafe', 'https://www.awfullychocolate.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (10, 'Dookki @ Suntec City', 'Dookki is a Korean restaurant that serves Tteokbokki Hotpot Buffet. It starts off with the Korean Hotpot style and ends with Kimchi Fried Rice. The wonderful and flavourful meal will definitely make you want more!.', 'images/t_dookki.jpg', 'images/img_dookki.jpg', '3 Temasek Blvd, #B1-107, Singapore 038984', '11.30am - 10.30am', '6266 2425', '$$', 'Korean', 'Central', 'Dinner', '4 Star', 'Restaurant', 'https://www.facebook.com/dookkisg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (11, 'Eighteen Chefs @ Our Tampines Hub', 'Eighteen Chefs is a local restaurant and franchise company in Singapore opened by an ex-offender Benny Se Teo in 2007. The restaurant serves western foods such as Baked Rice and Pasta and some other local cusine dishes at very affordable prices. They also have daily student and NSF set meals which makes it very popular among the younger generation.', 'images/t_18chefs.jpg', 'images/img_18chefs.jpg', '51 Tampines Avenue 4, 1 Tampines Walk, #02-90/91, 520940', '11am - 10pm', '6214 9655', '$', 'Western', 'East', 'Lunch', '3 Star', 'Restaurant', 'https://www.eighteenchefs.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (12, 'Saizeriya @ JCube', 'Saizeriya is a restaurant which serves italian food at ridiculously-cheap prices. It also offers a wide variety of dishes so there will definitely be something for everyone. The restaurant also has a very comfortable and nice ambience.', 'images/t_saizeriya.jpg', 'images/img_saizeriya.jpg', '2 Jurong East Central 1, #02-09B JCube, Singapore 609731', '11am - 9.30pm', '6268 7512', '$', 'Italian', 'West', 'Lunch', '4 Star', 'Restaurant', 'https://www.saizeriya.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (13, 'PS.Cafe Petit @ Tiong Bahru', 'PS. Cafe Petit is a gourmet takeaway retail concept reataurant which provides traditional fast foods like Pizza, Burgers and hearty salads with a cozy ambience.', 'images/t_pscafe.jpg', 'images/img_pscafe.jpg', '78 Guan Chuan St, No.41 Blk, Singapore 160078', 'Weekdays: 11am - 11pm, Weekends: 9.30am - 11pm', '6708 9288', '$$$', 'Italian', 'Central', 'Breakfast', '4 Star', 'Restaurant', 'https://www.pscafe.com/pscafe-petit-at-tiong-bahru');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (14, 'An Acai Affair @ WestGate', 'Acai Affair is started by 2 friends who share the same love for acai. The dessert is organic and preservatives-free which makes it healthy. An Acai Affair does not use any artificial products in their acai which makes the yummy dessert very low in calories.', 'images/t_acai.jpg', 'images/img_acai.jpg', '3 Gateway Dr, #B1-30 Westgate, Singapore 608532', '11.30am - 10pm', 'N.A.', '$$', 'Brazillian', 'West', 'Dessert', '5 Star', 'Cafe', 'https://www.anacaiaffair.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (15, 'Timbre+', 'Timbre+ is an urban container food park with a wide variety of food stalls of different cuisines. In the evening, Timbre+ also has live bands playing which makes it a great chill-out and catch up location for you and your friends.', 'images/t_timbre.jpg', 'images/img_timbre.jpg', '73A Ayer Rajah Crescent, JTC Launchpad, Singapore 139957', 'Monday-Saturday: 6am - 12am, Sunday: 11am - 10pm', '6252 2545', '$$', 'Variety', 'West', 'Nightlife', '4 Star', 'Hawker, Bar', 'https://timbreplus.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (16, 'iSteaks Diner @ Tampines 1', 'iSteaks is a steak house which serves a variety of western dishes ranging from Beef and Chicken steaks to Salmon steaks.', 'images/t_isteaks.jpg', 'images/img_isteaks.jpg', '10 Tampines Central 1, #04-04/05, Singapore 529536', '11am - 10pm', '6285 8839', '$$', 'Western', 'East', 'Dinner', '4 Star', 'Restaurant', 'https://www.isteaksdiner.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (17, 'Astons Specialities @ Sembawang Shopping Centre', 'Astons serves a variety of delicious western foods with beef, fish, chicken etc. Their dishes are all value for money as it is all of quality and it is very tasty!', 'images/t_astons.jpg', 'images/img_astons.jpg', '604 Sembawang Rd, #B1-12/13/14, Singapore 758459', '11.30am- 10pm', '6753 6302', '$$', 'Western', 'North', 'Lunch', '4 Star', 'Restaurant', 'http://www.astons.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (18, 'Ya Kun Kaya Toast @ Compass One', 'Ya Kun Kaya Toast is a household brand here in sunny Singapore and Asia. It offers delectable kaya toast and other traditional breakfast dishes. Ya Kun Kaya Toast also serves aromatic coffee alongside their breakfast dishes. It also serves local dishes such as Laksa, Mee Rebus, and many more!', 'images/t_yakun.jpg', 'images/img_yakun.jpg', '1 Sengkang Square, #01-37 Compass One, Singapore 545078', '7.30am - 10pm', '6386 4165', '$', 'Variety', 'North-East', 'Breakfast', '4 Star', 'Cafe', 'http://yakun.com/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (19, 'ThaiLily Restaurant @ Toa Payoh', 'ThaiLily serves mouth-watering authentic thai dishes.', 'images/t_thailily.jpg', 'images/img_thailily.jpg', 'oa Payoh Block 107 Lorong 1#01-268', '11am - 11pm', '6253 8231', '$$', 'Thai', 'Central', 'Dinner', '4 Star', 'Restaurant', 'https://www.facebook.com/thaililyrestaurantsingapore/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (20, '+82 PlusEightTwo', 'PlusEightTwo(+82) Cafe is opened by member EunKwang of one of the K-POP boybands BTOB. The cafe offers desserts like cake and bingsu on their menu together with their aromatic hot and iced coffee. On many days, the cafe is also being rented to local K-POP fansites to set up events to celebrate their idols birthday and anniversary.', 'images/t_+82.jpg', 'images/img_+82.jpg', '9, #01-02 Bras Basah Rd, Rendezvous Gallery, 189559', '9am - 11pm', '8535 7294', '$$', 'Korean', 'Central', 'Cafe', '5 Star', 'Cafe', 'https://www.facebook.com/pages/PLUS-EIGHT-TWO-82/320708255114479');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (21, 'Wok Hey @ White Sands', 'Wok Hey, Masters of stirfry. Dive into some scrumptious stir fried rice and noodles with Wok Hey! Wok Hey is a modern zi char stall which offers their meals in convenient takeaway boxes for their customers.', 'images/t_wokhey.jpg', 'images/img_wokhey.jpg', '1 Pasir Ris Drive 3, #B1-K05, Singapore 518457', '11am - 10pm', '6694 0088', '$', 'Chinese', 'East', 'Takeaway', '5 Star', 'Takeaway', 'https://www.facebook.com/wokheysg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (22, 'Canton Paradise @ The Star Vista', 'Canton Paradise offers a wide variety of dishes from the Hong Kong cuisine. Its dishes ranges from rice and noodles to hong kong dimsum. Its yummy dishes have attracted large crowds to their restaurants.', 'images/t_canton.jpg', 'images/img_canton.jpg', '1 Vista Exchange Green, #B1-45 The Star Vista, Singapore 138617', 'Weekdays: 11am - 9.30pm, Weekends: 10.30am - 9.30pm', '6694 2915', '$$$', 'Hong Kong', 'West', 'Dinner', '5 Star', 'Restaurant', 'https://www.paradisegp.com/brand-canton-paradise/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (23, 'Pepper Lunch @ Hougang Mall', 'Pepper Lunch serves rice with meat like beef, chicken and fish on hot plates. You can watch your scruptious meal sizzle your way before you dig in. Pepper Lunch has been popular among many individuals and have attracted many new customers!', 'images/t_pepperlunch.jpg', 'images/img_pepperlunch.jpg', ' 90 Hougang Ave 10, #B1-24 Hougang Mall, Singapore 538766', '11am -10pm', '6387 2800', '$$', 'Japanese', 'North-East', 'Lunch', '4 Star', 'Restaurant', 'https://www.pepperlunch.com.sg/');
INSERT into restaurant (`restaurant_id`, `restaurant_name`, `description`, `thumbnail`, `images`, `address`, `operating_hours`, `phone_number`, `cost`, `cuisine`, `region`, `category`, `overall_rating_star`, `establishment_type`, `website`) VALUES (24, 'Heap Seng Leong-Kaya Toasts & Kopi Gu Yau', 'Today, not many places in Singapore serves Kopi Gu Yau. Heap Seng Leong is a place which carries on this tradition of selling Kopi Gu Yau. They too serve traditional breakfast such as half boiled eggs and kaya toasts as well.', 'images/t_kopiguyau.jpg', 'images/img_kopiguyau.jpg', '10 North Bridge Rd, #01-5109, Singapore 190010', '4am - 8pm', '6292 2368', '$', 'Chinese', 'Central', 'Breakfast', '4 Star', 'Hawker', 'N.A.');
